from bs4 import BeautifulSoup
import requests
import re
import time

start_urls = 'http://cd.ganji.com/wu/'
def Find_url():
    wb_data = requests.get(start_urls)
    wb_data.encoding = 'urf-8'
    soup = BeautifulSoup(wb_data.text,'lxml')
    links = soup.select('div.main > ul  a')
    for link in links:
        # http://cd.ganji.com/ershoubijibendiannao/_macbook+pro/
        href = 'http://cd.ganji.com' + link.get('href')
        print(href)
# print()

url_list = """
http://cd.ganji.com/ershoubijibendiannao/_macbook+pro/
http://cd.ganji.com/ershoubijibendiannao/_macbook/
http://cd.ganji.com/iphone/
http://cd.ganji.com/ipodTouch/
http://cd.ganji.com/iphone-iphone-4s/
http://cd.ganji.com/mi-hongmi/
http://cd.ganji.com/sanxingshouji-galaxy-s-iv/
http://cd.ganji.com/sanxingshouji-galaxy-note-iii/
http://cd.ganji.com/pingguo/
http://cd.ganji.com/lianxiang/
http://cd.ganji.com/thinkpad/
http://cd.ganji.com/suoni/
http://cd.ganji.com/daier/
http://cd.ganji.com/huashuo/
http://cd.ganji.com/ershoubijibendiannao/_New+iPad/
http://cd.ganji.com/ershoubijibendiannao/_%E4%B9%90Pad/
http://cd.ganji.com/psv/
http://cd.ganji.com/shuma/_%E4%BD%B3%E8%83%BD/
http://cd.ganji.com/shuma/_%E5%B0%BC%E5%BA%B7/
http://cd.ganji.com/shuangrenchuang/
http://cd.ganji.com/dianfengshan/
http://cd.ganji.com/tongche/
http://cd.ganji.com/qunzi/
http://cd.ganji.com/fangshaishuang/
http://cd.ganji.com/iphone-iphone-5s/
http://cd.ganji.com/mi-hongminote/
http://cd.ganji.com/kongtiao/
http://cd.ganji.com/shouji/
http://cd.ganji.com/iphone/
http://cd.ganji.com/nokia/
http://cd.ganji.com/htc/
http://cd.ganji.com/sanxingshouji/
http://cd.ganji.com/motorola/
http://cd.ganji.com/suoniailixin/
http://cd.ganji.com/shouji/p1/
http://cd.ganji.com/shouji/b1000e1500/
http://cd.ganji.com/shoujihaoma/
http://cd.ganji.com/shoujihaoma/
http://cd.ganji.com/tongxuntaocan/
http://cd.ganji.com/qqhao/
http://cd.ganji.com/shoujipeijian/
http://cd.ganji.com/lanyaerji/
http://cd.ganji.com/shoujike/
http://cd.ganji.com/shoujidianchi/
http://cd.ganji.com/chongdianqi/
http://cd.ganji.com/bijibendiannao/
http://cd.ganji.com/pingbandiannao/z1/
http://cd.ganji.com/bijibendiannao/
http://cd.ganji.com/shangwangben/
http://cd.ganji.com/ershoubijibendiannao/_%E6%B8%B8%E6%88%8F%E6%9C%BA/
http://cd.ganji.com/ershoubijibendiannao/_%E5%95%86%E5%8A%A1%E6%9C%AC/
http://cd.ganji.com/bijibendiannao/b0e500/
http://cd.ganji.com/bijibendiannao/p3/
http://cd.ganji.com/ershoubijibendiannao/p4/
http://cd.ganji.com/taishidiannaozhengji/
http://cd.ganji.com/taishidiannaozhengji/
http://cd.ganji.com/yitiji/
http://cd.ganji.com/fuwuqi/
http://cd.ganji.com/diannaoyingjian/
http://cd.ganji.com/xianka/
http://cd.ganji.com/cpu/
http://cd.ganji.com/yingpan/
http://cd.ganji.com/xianshiqi/
http://cd.ganji.com/neicun/
http://cd.ganji.com/zhuban/
http://cd.ganji.com/wangluoshebei/
http://cd.ganji.com/wuxianluyouqi/
http://cd.ganji.com/yidongyingpan/
http://cd.ganji.com/diannaoyinxiang/
http://cd.ganji.com/dayinji/
http://cd.ganji.com/3gwangka/
http://cd.ganji.com/shumaxiangji/
http://cd.ganji.com/danfanxiangji/
http://cd.ganji.com/dandianxiangji/
http://cd.ganji.com/jingtou/
http://cd.ganji.com/shumashexiangji/
http://cd.ganji.com/youxiji/
http://cd.ganji.com/yueqiyinxiang/
http://cd.ganji.com/ipodTouch/
http://cd.ganji.com/psp/
http://cd.ganji.com/ps3/
http://cd.ganji.com/xuniwupin/
http://cd.ganji.com/zhanghaozhuangbei/
http://cd.ganji.com/chongzhidianka/
http://cd.ganji.com/qqhao/z1/
http://cd.ganji.com/shouji/
http://cd.ganji.com/bijibendiannao/
http://cd.ganji.com/taishidiannaozhengji/
http://cd.ganji.com/shumaxiangji/
http://cd.ganji.com/jiaju/
http://cd.ganji.com/chuangdian/
http://cd.ganji.com/guizi/
http://cd.ganji.com/zhuoyi/
http://cd.ganji.com/shafachaji/
http://cd.ganji.com/rirongbaihuo/
http://cd.ganji.com/bangongjiaju/
http://cd.ganji.com/jiaju/_%E6%90%AC%E5%AE%B6/
http://cd.ganji.com/jiaju/p1/
http://cd.ganji.com/jiadian/
http://cd.ganji.com/dianshi/
http://cd.ganji.com/bingxiang/
http://cd.ganji.com/kongtiao/
http://cd.ganji.com/reshuiqi/
http://cd.ganji.com/xiyiji/
http://cd.ganji.com/diancilu/
http://cd.ganji.com/weibolu/
http://cd.ganji.com/doujiangji/
http://cd.ganji.com/yueqiyinxiang/
http://cd.ganji.com/zixingchemaimai/
http://cd.ganji.com/zixingchemaimai/
http://cd.ganji.com/diandongche/
http://cd.ganji.com/motuoche/
http://cd.ganji.com/sanlunche/
http://cd.ganji.com/rirongbaihuo/
http://cd.ganji.com/anmobaojian/
http://cd.ganji.com/chuangshangyongpin/
http://cd.ganji.com/zhuangshibaishe/
http://cd.ganji.com/jiaju/
http://cd.ganji.com/jiadian/
http://cd.ganji.com/zixingchemaimai/
http://cd.ganji.com/motuoche/
http://cd.ganji.com/yingyouyunfu/
http://cd.ganji.com/yingerche/
http://cd.ganji.com/niuniuche/
http://cd.ganji.com/xuebuche/
http://cd.ganji.com/ertonganquanzuoyi/
http://cd.ganji.com/yingerchuang/z1/
http://cd.ganji.com/niaobushi/
http://cd.ganji.com/naifen/
http://cd.ganji.com/tongche/
http://cd.ganji.com/tongzhuang/
http://cd.ganji.com/wanju/
http://cd.ganji.com/fushixiaobaxuemao/
http://cd.ganji.com/qunzi/
http://cd.ganji.com/gaogenxie/
http://cd.ganji.com/liangxie/
http://cd.ganji.com/shoubiao/
http://cd.ganji.com/shipin/
http://cd.ganji.com/lvxingxiang/
http://cd.ganji.com/danjianbao/
http://cd.ganji.com/shuangjianbao/
http://cd.ganji.com/shoutibao/
http://cd.ganji.com/meironghuazhuang/
http://cd.ganji.com/xiangshui/
http://cd.ganji.com/fangshaishuang/
http://cd.ganji.com/huazhuangpin/
http://cd.ganji.com/hufupin/
http://cd.ganji.com/yingyouyunfu/
http://cd.ganji.com/fushixiaobaxuemao/
http://cd.ganji.com/meironghuazhuang/
http://cd.ganji.com/yundongqicai/
http://cd.ganji.com/paobuji/
http://cd.ganji.com/yaling/
http://cd.ganji.com/yumaoqiuqicai/
http://cd.ganji.com/shoufuji/z1/
http://cd.ganji.com/yueqi/
http://cd.ganji.com/jita/
http://cd.ganji.com/gangqin/
http://cd.ganji.com/dianziqin/
http://cd.ganji.com/tushu/
http://cd.ganji.com/zhuanyejishushuji/
http://cd.ganji.com/kaoshijiaofu/
http://cd.ganji.com/xiaoshuowenxue/
http://cd.ganji.com/yundongqicai/
http://cd.ganji.com/yueqi/
http://cd.ganji.com/tushu/
http://cd.ganji.com/bangongjiaju/
http://cd.ganji.com/jiguangyitiji/
http://cd.ganji.com/dayinji/
http://cd.ganji.com/bangongzhuo/
http://cd.ganji.com/diannaozhuo/
http://cd.ganji.com/huojiazhanjia/z1/
http://cd.ganji.com/wujingongju/
http://cd.ganji.com/jichuang/
http://cd.ganji.com/fengrenji/
http://cd.ganji.com/fadianji/
http://cd.ganji.com/shipinjiagongshebei/
http://cd.ganji.com/gongjuwujin/
http://cd.ganji.com/nongyongpin/
http://cd.ganji.com/nongyongjixie/
http://cd.ganji.com/tuolaji/
http://cd.ganji.com/shucaishuiguo/
http://cd.ganji.com/miaomu/
http://cd.ganji.com/bangongjiaju/
http://cd.ganji.com/dayinji/
http://cd.ganji.com/wujingongju/
http://cd.ganji.com/xianzhilipin/
http://cd.ganji.com/qitalipinzhuanrang/
http://cd.ganji.com/kalei/
http://cd.ganji.com/shoubiao/
http://cd.ganji.com/jiu/
http://cd.ganji.com/chaye/
http://cd.ganji.com/shougongshizixiu/
http://cd.ganji.com/shoucangpin/
http://cd.ganji.com/youpiao/
http://cd.ganji.com/guwan/
http://cd.ganji.com/jinyinzhuyu/
http://cd.ganji.com/gongyipin/
http://cd.ganji.com/baojianpin/
http://cd.ganji.com/dongchongxiacao/
http://cd.ganji.com/kafeizhuanrang/
http://cd.ganji.com/haishen/
http://cd.ganji.com/rencan/
http://cd.ganji.com/fengmi/
http://cd.ganji.com/laonianyongpin/
http://cd.ganji.com/anmobaojian/z1/
http://cd.ganji.com/zibubaojian/z2/
http://cd.ganji.com/bawanwujian/
http://cd.ganji.com/xianzhilipin/
http://cd.ganji.com/shoucangpin/
http://cd.ganji.com/baojianpin/
http://cd.ganji.com/qitawupin/
http://cd.ganji.com/gou/
http://cd.ganji.com/zangao/
http://cd.ganji.com/taidixiong/
http://cd.ganji.com/jinmao/
http://cd.ganji.com/hashiqi/
http://cd.ganji.com/dog/
http://cd.ganji.com/chongwupeizhong/
http://cd.ganji.com/qitaxiaochong/
http://cd.ganji.com/mao/
http://cd.ganji.com/longmao/
http://cd.ganji.com/jinli/
http://cd.ganji.com/yingwu/
http://cd.ganji.com/cangshu/
http://cd.ganji.com/qitaxiaochong/_%E5%85%94%E5%AD%90/
http://cd.ganji.com/xiaofeika/
http://cd.ganji.com/gouwuka/
http://cd.ganji.com/daijinquan/
http://cd.ganji.com/jianshenka/
http://cd.ganji.com/youyongka/
http://cd.ganji.com/menpiao/
http://cd.ganji.com/dianyingpiao/
http://cd.ganji.com/jingdianmenpiao/
http://cd.ganji.com/yanchanghuimenpiao/
http://cd.ganji.com/tiyusaishi/
http://cd.ganji.com/gou/
http://cd.ganji.com/qitaxiaochong/
http://cd.ganji.com/gouwuka/
http://cd.ganji.com/dianyingpiao/
"""
Find_url()
